//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36365
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSWebApp.EmployeeServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeEntitity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EmployeeEntitity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int employeeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string extensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string officeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reportsToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int employeeNumber {
            get {
                return this.employeeNumberField;
            }
            set {
                if ((this.employeeNumberField.Equals(value) != true)) {
                    this.employeeNumberField = value;
                    this.RaisePropertyChanged("employeeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                if ((object.ReferenceEquals(this.extensionField, value) != true)) {
                    this.extensionField = value;
                    this.RaisePropertyChanged("extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string officeCode {
            get {
                return this.officeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.officeCodeField, value) != true)) {
                    this.officeCodeField = value;
                    this.RaisePropertyChanged("officeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string jobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.jobTitleField, value) != true)) {
                    this.jobTitleField = value;
                    this.RaisePropertyChanged("jobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string reportsTo {
            get {
                return this.reportsToField;
            }
            set {
                if ((object.ReferenceEquals(this.reportsToField, value) != true)) {
                    this.reportsToField = value;
                    this.RaisePropertyChanged("reportsTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceRef.EmployeeServiceSoap")]
    public interface EmployeeServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        AWSWebApp.EmployeeServiceRef.GetAllEmployeesResponse GetAllEmployees(AWSWebApp.EmployeeServiceRef.GetAllEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployees", Namespace="http://tempuri.org/", Order=0)]
        public AWSWebApp.EmployeeServiceRef.GetAllEmployeesRequestBody Body;
        
        public GetAllEmployeesRequest() {
        }
        
        public GetAllEmployeesRequest(AWSWebApp.EmployeeServiceRef.GetAllEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllEmployeesRequestBody {
        
        public GetAllEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public AWSWebApp.EmployeeServiceRef.GetAllEmployeesResponseBody Body;
        
        public GetAllEmployeesResponse() {
        }
        
        public GetAllEmployeesResponse(AWSWebApp.EmployeeServiceRef.GetAllEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<AWSWebApp.EmployeeServiceRef.EmployeeEntitity> GetAllEmployeesResult;
        
        public GetAllEmployeesResponseBody() {
        }
        
        public GetAllEmployeesResponseBody(System.Collections.Generic.List<AWSWebApp.EmployeeServiceRef.EmployeeEntitity> GetAllEmployeesResult) {
            this.GetAllEmployeesResult = GetAllEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceSoapChannel : AWSWebApp.EmployeeServiceRef.EmployeeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceSoapClient : System.ServiceModel.ClientBase<AWSWebApp.EmployeeServiceRef.EmployeeServiceSoap>, AWSWebApp.EmployeeServiceRef.EmployeeServiceSoap {
        
        public EmployeeServiceSoapClient() {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AWSWebApp.EmployeeServiceRef.GetAllEmployeesResponse AWSWebApp.EmployeeServiceRef.EmployeeServiceSoap.GetAllEmployees(AWSWebApp.EmployeeServiceRef.GetAllEmployeesRequest request) {
            return base.Channel.GetAllEmployees(request);
        }
        
        public System.Collections.Generic.List<AWSWebApp.EmployeeServiceRef.EmployeeEntitity> GetAllEmployees() {
            AWSWebApp.EmployeeServiceRef.GetAllEmployeesRequest inValue = new AWSWebApp.EmployeeServiceRef.GetAllEmployeesRequest();
            inValue.Body = new AWSWebApp.EmployeeServiceRef.GetAllEmployeesRequestBody();
            AWSWebApp.EmployeeServiceRef.GetAllEmployeesResponse retVal = ((AWSWebApp.EmployeeServiceRef.EmployeeServiceSoap)(this)).GetAllEmployees(inValue);
            return retVal.Body.GetAllEmployeesResult;
        }
    }
}
